version: 2
jobs:
  build:
    working_directory: ~/example-foobar
    docker:
      - image: ruby:2.4
        environment:
          CODECLIMATE_REPO_TOKEN: "d95f1200dc240490352a6e5d21dc218d02c1bddb77d710b5ebc436ecb07e43bc"
    steps:
      - checkout
      - type: cache-restore
        key: example-foobar-{{ checksum "Gemfile.lock" }}
      - run: bundle install --path vendor/bundle
      - type: cache-save
        key: example-foobar-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle
      - run: bundle exec rspec && bundle exec codeclimate-test-reporter
